export const ownerCredentials = [
  {
    key: "fullName",
    label: "Full Name",
    placeholder: "Enter your full name",
    required: true,
  },
  {
    key: "mail",
    label: "Email Address",
    placeholder: "example@mail.com",
    required: true,
  },
  {
    key: "phone",
    label: "Phone Number",
    placeholder: "+27 600 000 000",
    required: true,
  },
  {
    key: "password",
    label: "Password",
    placeholder: "Enter a secure password",
    required: true,
  },
  {
    key: "confirmPassword",
    label: "Confirm Password",
    placeholder: "Re-enter your password",
    required: true,
  },
  {
    key: "proofOfOwnership",
    label: "Proof of Car Ownership",
    placeholder: "Upload logbook or title document",
    required: true,
  },
  {
    key: "faceCaptureVerification",
    label: "Face Capture & Ownership Document Comparison",
    placeholder: "Take a selfie for identity verification",
    required: true,
  },
  {
    key: "carPictureWithPlate",
    label: "Picture of Car Showing License Plate",
    placeholder: "Upload a photo clearly showing the license plate",
    required: true,
  },
  {
    key: "registrationDisk",
    label: "Registration Disk",
    placeholder: "Upload a photo of the car's registration disk",
    required: true,
  },
  {
    key: "decra",
    label: "DECRA Report",
    placeholder: "Upload your latest DECRA report",
    required: true,
  },
  {
    key: "rentalValue",
    label: "Rental Value Per Week",
    placeholder: "Enter rental value (e.g. R1500)",
    required: true,
  },
  {
    key: "rentalDeposit",
    label: "Rental Deposit",
    placeholder: "Enter deposit amount (e.g. R3000)",
    required: true,
  },
  {
    key: "isInsured",
    label: "Is the Car Insured?",
    placeholder: "Yes or No",
    type: "boolean",
    options: [
      { label: "True", value: true },
      { label: "False", value: false },
    ],
    required: true,
  },
  {
    key: "hasTracker",
    label: "Does the Car Have a Tracker?",
    placeholder: "Yes or No",
    type: "boolean",
    options: [
      { label: "True", value: true },
      { label: "False", value: false },
    ],
    required: true,
  },
  {
    key: "hasDashCam",
    label: "Is the Car Using a Dash Cam?",
    placeholder: "Yes or No",
    type: "boolean",
    options: [
      { label: "True", value: true },
      { label: "False", value: false },
    ],
    required: true,
  },
  {
    key: "mileage",
    label: "Current Mileage",
    placeholder: "Enter mileage (e.g. 85,000 km)",
    required: true,
  },
  {
    key: "engineSize",
    label: "Engine Size",
    placeholder: "Enter engine size (e.g. 1.4L)",
    required: true,
  },
];
